spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: Ksijb0109!  
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: gestion-enrolamiento

springdoc:
  api-docs:
    path: /srv-gestion-solicitud-openapi
    
server:
  port : 8082

bolivar:
  api:
    doc:
      apiVersion: 1.0
      apiDescription: Administración de Datos de la Solicitud
      apiTitle: Servicio Atómico Administración de Solicitudes
      apiServers:
        -
          url: urldev/gestion-enrolamiento
          description: DEV
        -
          url: urlstage/gestion-enrolamiento
          description: STAGE
        -
          url: urlprod/gestion-enrolamiento
          description: PROD